# See https://hub.docker.com/r/cdstelly/probe/
# look into requivalend kuernetes version
FROM ubuntu:trusty
MAINTAINER cdstelly <cdstelly@gmail.com
RUN apt-get update

RUN apt-get install -y curl make g++ gcc netcat dnsutils

CMD ["netcat", "-l", "1234"]


# get the container running the probe
function gp() {
        psid=$(docker service ls | grep probe | awk '{print $1}')
        docker service ps $psid | awk '{print $4}' | tail -n 1
}

# shortcut to do a shell on either the specified container, if given, or on the first one
function e () {
        container=$1
        if [[ $# -eq 0 ]] ; then
                container=$(docker ps | awk '{print $1}' | head -n 2 | tail -n 1)
        fi
        docker exec -it $container/bin/sh
}


